### PR TITLE
master: update release-tools

### PR DESCRIPTION
**Pull request by pohly**
Commit summary:
1eaaaa1c Delete kind cluster after tests run.
f41c1351 prow.sh: also log output of system containers

```release-note
NONE
```

### CODE REVIEW

**Comment by msau42** [comment]
There have been more changes, do you want to include those too?

**Comment by pohly** [comment]
> There have been more changes, do you want to include those too?

The script from https://github.com/kubernetes-csi/csi-release-tools/issues/7 doesn't handle updating an existing PR, so no, I would prefer to merge this as-is and later to another round of updates. Also, that way the different repos remain consistent.

**Comment by pohly** [comment]
> Also, that way the different repos remain consistent.

They don't need to be, it's just a bit easier to track status when they are...

**Pull request merged**
