### PR TITLE
Automated cherry pick of #243: Fix CVE and update dependencies to the latest

### PR DESCRIPTION
**Pull request by knopt**
Cherry pick of #243 on release-2.6.

#243: Fix CVE and update dependencies to the latest

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

```release-note

```

### CODE REVIEW

**Comment by knopt** [comment]
@mauriciopoppe @humblec  could you please have a look?

**Review by pohly — APPROVED** [review]
/lgtm

**Comment by mauriciopoppe** [comment]
/assign @msau42 
I think I might need to do another release e.g. v2.6.3

**Comment by knopt** [comment]
@msau42 does this MR look ok for you?

**Comment by knopt** [comment]
Anyone able to approve the MR?

**Comment by humblec** [comment]
@knopt PR is pretty much in approved state, to be in effect we need a release . Thats what we are checking with @msau42 .

**Pull request merged**
