### PR TITLE
bump pluginregistration api version to v1

### PR DESCRIPTION
**Pull request by gnufied**
We have been using v1alpha1 version for far too long. 

cc @msau42 @jsafrane 

```release-note
Use v1 API for plugin registration with kubelet
```

### CODE REVIEW

**Comment by humblec** [comment]
@gnufied can you move to `v0.19.0-rc.2` as part of this PR?

**Comment by gnufied** [comment]
@humblec why? I would leave it at a released version, there is literally no change in API, the main thing is we want to stop using v1alpha1

**Comment by jsafrane** [comment]
Is this a breaking change? The registrar stops working in Kubernetes v1.13. It's OK to break it, however, we should probably bump the registrar to v2.

**Comment by jsafrane** [comment]
Filed https://github.com/kubernetes-csi/node-driver-registrar/issues/97

**Comment by humblec** [comment]
> @humblec why? I would leave it at a released version, there is literally no change in API, the main thing is we want to stop using v1alpha1

sure.. :).. I thought we are going to update this anyway to 1.19 soon. Thats why I mentioned we could try now itself :)

**Pull request merged**
